### PR TITLE
Copy script from `AgentDesktop` to `Build Harness`

### PR DESCRIPTION
**Pull request by aargonda**
### What

Copy `do-exclusively.sh` to `Build harness` as `circle-do-exclusively.sh` so it can be shared among different repositories

### Who

@darend 

JIRA: DEV-4756

### CODE REVIEW

**Comment by darend** [comment]
- [ ] make sure the script has `+x` set for execution
- +2

**Comment by aargonda** [comment]
>make sure the script has +x set for execution

Verified
1__zsh

**Comment by osterman** [comment]
@darend, @aargonda: I agree with adding this logic to the script, but any reason why we're not using `Makefile.circle` to define a target for calling it? The main benefits for using the `Makefile` is so that the interface is consistent; the underlying commands can change, but consumers don't need to care making maintenance easier.

**Comment by osterman** [comment]
I suggest adding a target:
```
circle:deploy-kubernetes:
  $(call assert,CIRCLE_BRANCH)
  @$(MAKEFILE_DIR)/bin/circle-do-exclusively.sh --branch $CIRCLE_BRANCH $(SELF) kubernetes:info kubernetes:deploy
```
(or something like that)

**Comment by darend** [comment]
Doh it did no even occur to me

Great idea

**Comment by osterman** [comment]
I'll add this. I need to fix something else apparently since this failed: https://circleci.com/gh/sagansystems/synthetic/87

**Pull request merged**
